### ISSUE TITLE
copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/timelapse-setup#6]
Hi @lauraclay or @LornaLynch 
I've branched this repo and completely rewritten the worksheet and updated all the configs, so I doubt it will be worth looking at the diffs on this one. If I could get a clean copy edit that would be great.
https://github.com/raspberrypilearning/timelapse-setup/blob/update/worksheet.md

**Comment by LornaLynch** [comment]
I'll make a start now, but I can't promise I'll get through it all without collapsing. @lauraclay, if you're around tomorrow, feel free to pick up from the last edit. Otherwise, I'll carry on when R lets me.

**Comment by MarcScott** [comment]
@LornaLynch It's nearly 9pm, so I'm not going to be publishing tonight. This can most definitely be left until tomorrow or Friday at the earliest.

**Comment by LornaLynch** [comment]
NB the link to the File Manager icon (near the selfie) is broken, but I'm guessing that's because this is a branch?

**Comment by MarcScott** [comment]
Fixed the broken image link

**Comment by LornaLynch** [comment]
Cheers!

**Comment by LornaLynch** [comment]
Link to Imagemagick software setup guide isn't working either... Sorry: can't see the file in this branch or the master.

**Comment by LornaLynch** [comment]
OK: copy edit on the worksheet is done :) 

Link to software setup guide remains a mystery though.

**Comment by MarcScott** [comment]
It's there now - thank you

**Comment by lauraclay** [comment]
Reopening - this is one of the resources I missed while my emails weren't getting to me last week. There are still errors that need fixing.
